# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aafcb31f6121e17d5d42727b7bd16081b825b2f9e8eaa6102e7b6c121ac60a4bb5695d23e97b0dd23d2bd64c38c5da29d3424d55e24d60f8d674e7b3d8a6dac

test:
  secret_key_base: 6cf7030ce809e67f8271de9b0d4eb4c8f98b9f24cfd1dbd224f9c29a927baaa04ad18f41f3a3f51919abfd9be10be657650f1a9159f0463e9bf4c41f776e8840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
